version: '2'

services:
  ttdatastore:
    image: ttdatastore
    build:
      context: ./ttdatastore
    ports:
      - '3301:3301'
    volumes:
      - ./data:/var/lib/tarantool
      - ./:/home/src

  imagehoster:
    image: imagehoster
    build:
      context: src
    ports:
      - '80'
    environment:
      - UPLOAD_STEEMD_WEBSOCKET
      - UPLOAD_AWS_KEY_ID
      - UPLOAD_AWS_SECRET_KEY
      - UPLOAD_TEST_KEY
