version: '3.6'
services:
  imagehoster:
    container_name: imagehoster_node
    image: imagehoster
    restart: always
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $HOST_PORT:80
    env_file:
      - .env
    volumes:
      - uploads_vol:/data/uploads
      - cache_vol:/data/cache

  mongo:
    container_name: imagehoster_mongo
    image: mongo:4
    restart: always
    # ports:
    #   - 27017:27017
    volumes:
      - mongodb_vol:/data/db

volumes:
  uploads_vol:
  cache_vol:
  mongodb_vol:
