version: '3.6'
services:
  imagehoster:
    container_name: imagehoster_node
    image: imagehoster
    restart: always
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $HOST_PORT:80
    env_file:
      - .env
    volumes:
      - files_vol:/data/files

  mongo:
    container_name: imagehoster_mongo
    image: mongo:4
    restart: always
    ports:
      - $MONGO_EXTRERNAL_PORT:27017
    volumes:
      - mongodb_vol:/data/db

volumes:
  files_vol:
  mongodb_vol:
